[project]
name = "ai-sample"
version = "0.1.0"
description = "A collection of python scripts doing AI stuff"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=0.3.0",
]
